global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA3TWW5WGMQX62F44C
        secret_key: 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
        port: 9100
